name: kafil
description: "Kafil Hiring Test"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Data:
  connectivity_plus: ^5.0.2
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  drift: ^2.16.0
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0

  #Domain:
  equatable: ^2.0.5
  dartz: ^0.10.1

  #Presentation-State:
  flutter_bloc: ^8.1.4
  provider: ^6.1.2

  #Dependency Injection:
  get_it: ^7.6.7

  #Util:
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf